<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
</head><?php

$accounts= mysql_connect("baseballforlife.db.9357957.hostedresource.com","baseballforlife", "Mattingly2327") 
or die (mysql_error());

mysql_select_db("baseballforlife", $accounts);


$sql=("INSERT INTO PowerRankings(Week, Date ,Rank,Team, Record, LastWeek,Move,Comments,Stud,Dud) 
VALUES('15','July 23-29','1','Seth B. Altshuler','','1','---','The fisherman keeps rolling. First my apologies for half-assing it here last week and somehow missing putting up Mike Trout\'s insane stat line (13R/3HRs/7RBIs/5SBs/1.368 OPS). Ok now that this is out of the way I will just throw a couple stats down for you. This team ranks in the top 2 in Rs, HRs, and SBs. They are third in OPS and fourth in RBIs. They rank in the top 2 in Saves, ERA and WHIP. To sum it up they rank in the top 2 in 6 categories. That is why they are in the top half, and are starting to pull away from the pack for the regular season title. In a down week for Mike Trout where he was unable to steal a base, the team still racked up ten of them while blasting 13Hrs (Willingham leading the way with 4) and sweeping all the offensive stats. Outside of Cliff Lee no one on the team posted an ERA over 3.00.','Jeff Samardzija (14IP/1Win/12Ks/1.29 ERA/0.79 WHIP) ','Cliff Lee (7IP/0Win/6Ks/7.71 ERA/1.86 WHIP) '),
('15','July 23-29','2','Mark Colantoni','','3','+1','Adam Dunn and Ryan Braun led the way this week as the Moose was able to sweep all five offensive categories. Clay Kershaw\'s big 2nd start was probably what put the team over the top in ERA and but Ben Sheets solid 6-Inning winning performance was important too. The pick up of Sheets has already paid off for the Moose softening the blow caused by the DL stint of Johan Santana. Can he keep this up remains to be seen, but he is providing some stability, which after Kershaw the rest of this rotation seems to lack.','Adam Dunn (9R/3HRs/8RBIs/SB/1.256 OPS) ','Mike Moustakas (Zeroes Across the Board/.372 OPS – Not reppin\' his team name too well)'),
('15','July 23-29','3','Rob Gleason','','4','+1','It wasn\'t pretty but the Pushovers did enough this week to win and jump up the standings into 3rd place. The offense was down this week with only 4Hrs, but still grabbed 3 of the 5 categories. Alicedes Escobar\'s 3 steals won the SB category by himself. The pitching really wasn\'t that great either but won 4 of the 5 categories and tied the other, lead by newly acquired Zack Greinke and waiver wire pick-up Mike Fiers, who combied pitched 20.1IP giving up 3ERs and racking up 22Ks, despite only registering 1 win.','Zack Greinke (14IP/0W/13Ks/1.93 ERA/0.79 WHIP) ','Robinson Cano (2R/0HR/0RBIs/.528OPS) '),
('15','July 23-29','4','Kevin O\'Brien','','5','+1','The team is starting to find its offense belting 12 homeruns. A healthy Michael Morse has 3HR/9RBIs and a healthy Chase Utley with 2HR/5RBIs/2SBs. The addition of these players is just as good as a trade if not better since you have given up nothing to get them. The Jews are finally getting rewarded for their hard work earlier in the year when they had to depend a great deal on their pitching. Oh and in regards to their pitching… the Irish Jews rank in the Top 2 in every pitching category. When you field a top 4 of Price, Hamels, CC and Gio then you usually will be in good shape. When it comes to the playoff race they are going to be in a multiple team battle, but they can now battle at full strength (unless I just threw a horrible jinx on your team)','Jose Reyes (6R/2HRs/5RBIs/3SBs/1.344 OPS) ','Jacoby Ellsbury (2R/0HR/0RBI/0SB/.546 OPS) '),
('15','July 23-29','5','Dave Waldstein','','2','-3','The offense was not horrible with 7 of the 9 hitters going yard, but no one person stepped up to lead the team (no one hitting more then 1 homerun). The other problem seems to be that besides Strasburg no one else can pitch right now. Is Doc still hurt? Was Harrison ever really as good as his W-L record said? Who is Travis Blackley? If the team had a little more strength on offense these questions would be as pressing. The bats didn\'t do it this week but with a re-energized Youk, a newly acquired Trumbo, 1st Round pick Prince Fielder and even J-Koobz the potential is there.','Stephen Strasburg (7IP/1Win/11Ks/1.29 ERA/0.57 WHIP)','Mark Trumbo (R/0HR/3RBIs/.634 OPS) '),
('15','July 23-29','6','Eric Waldstein','','7','+1','There are a few teams that could make a case for the final spot in the top half of the rankings. I decided to give it to a team that won this past week in Chagrin. They sit right on the brink in this playoff battle and pulled out a 5-4-1 win over one of the other contenders. Victorino\'s 3 steals were key in giving Chagrin one of their two wins on the offensive side. The duo of Kimbrel and Jansen continue to shine with their 4 saves giving them the win there. Their 0ERs in 4IP, helped pad the great starts from Chad Billingsley and Jay Vargas to give them wins in ERA and WHIP too.','Chad Billingsley (13.1IP/2Wins/6Ks/0.68 ERA/ 0.90 WHIP) ','Anibal Sanchez (6IP/0Win/3Ks/7.50 ERA/1.83 WHIP) '),
('15','July 23-29','7','Dave Majofsky','','10','+3','Just when it looked like the season was over the Sucks got a new life, with a 10-0 white washing of the TipToes, catapulting them right back into the thick of things. The offense pulled off tight wins in Runs and RBIs, lead by strong performances from Corey Hart and David Wright. Wright\'s OPS might have been putrid but he still put numbers up across the board including a stolen base. Although the TipToes had King Felix and Justin Verlander, the Sucks left little doubt who had the better week on the mound. Aroldis Chapman posted 4Saves and 8Ks over 4 scoreless innings. Starters like Hiroki Kuroda, CJ Wilson and Josh Johnson all took advantage of their two starts each positng double digit Ks. Now that they are relevant again we will see if they can keep the momentum going as we head toward the final month of the fantasy regular season.','Josh Johnson (11IP/1Win/13Ks/0.82 ERA/0.82 WHIP) ','Aaron Hill (2R/0HRs/2RBIs/.530 OPS) '),
('15','July 23-29','8','Chris Mantione','','9','+1','This team keeps putting up some really weird stats. How do you double-up you opponent in homeruns (16-8) but still lose OPS? The Smack found a way to pull it off, and in turn lost a very important playoff-implications match 4-5-1. Still the one great bright side here is that the pitching was better. The staff kept their ERA under 4.00 and their WHIP really wasn\'t that bad either (1.133). The additions of Homer Bailey and Adam Wainwright have already shown to be huge as they posted a combined stat line of (20.1IP/4ER/1 Win/19Ks. That catapults them right to the top of the staff, especially with the way J. McDonald has begun to struggle.','Ike Davis (6R/6HRs/6RBIs, so yes 6 Solo Homeruns, no one gets on base for this guy somehow/ 1.172 OPS)','Josh Hamilton (2R/0HRs/5RBIs/.315 OPS – not the time to be disappearing)'),
('15','July 23-29','9','Matt Stockwell','','8','-1','The pitching had a down week. If this team is going to win that kinda can\'t happen. In my opinion this team is one of the top 3 pitching staffs in the league but they can\'t produce every week. Although they did win HRs and RBIs, the OPS was still below .700. The pitching should bounce back. This should allow them to stay in the thick of it for one of these final spots. ','Ryan Vogelsong (13IP/W/11Ks/1.38 ERA/1.23 WHIP) ','Jim Johnson (1.1IP/0Ks/0Wins/0Saves/40.50 ERA/6.00 WHIP)'),
('15','July 23-29','10','Arjun Rajeev','','6','-4','Well that should just about do it for the Joe\'s. And so ends my personal pilgrimage to bring relevance to their season. I can no longer put them near the top half after the beating they took from the Jews. Although some categories were close (RBIs, OPS, Ks, Saves) they were unable to grab any of them and in turn lost 1-8-1. We will see what the rest of the season has in store, but still the future seems to be bright for players such as Jason Heyward and David Freese who both put up solid numbers for the week. The injury to A-Rod was a rough blow for the team. It also didn\'t help that Lincecum continued to be inconsistent at a horrible time when Capuano finally had a down week.','Adam LaRoche (4R/3HRs/6RBIs/1.253 OPS) ','Dan Uggla (1R/0HR/1RBI/.356 OPS) '),
('15','July 23-29','11','Jay Kondas','','11','---','They were just another helpless victim against the wrath of the Fisherman. Signs of life from supposed fantasy stud catcher, Carlos Santana, are nice but a bit too late. The same can be said on the pitching end with Ian Kennedy. It is time to just build toward the future.','Ian Kennedy (14.1IP/2Wins/16Ks/3.14 ERA/0.91 WHIP) ','Jason Kipnis (R/0HRs/2RBIs/0SB/.566 OPS) '),
('15','July 23-29','12','Jeff Stern','','12','---','This week\'s shutout loss can just be added to the list of downers for the TipToes. The future can\'t come soon enough for this club. I will give a quick shout out to the Butler though. Through all the negativity and criticism given to this organization he has continued to handle himself in a professional manner while putting together a very solid season.','Billy Butler (4R/HR/6RBIs/1.260 OPS) ','James Shields (6IP/0Wins/10Ks/7.50 ERA/1.83 WHIP)');

");
mysql_query($sql, $accounts);//(variable, connection)

?>